### PR TITLE
Fix notifications spec trashing the comment

### LINKED ISSUE #535: Delete comment step in notifications spec not consistently deleting the comment
The notifications spec ends with a step to delete the comment that was just left on the test site: https://github.com/Automattic/wp-e2e-tests/blob/master/specs/wp-notifications-spec.js#L98

However, even though that test is passing, the comments aren't being deleted. The test site has pending comments from this test — currently, the oldest pending comment is from 2017/03/16 at 10:02 pm.

I did a manual test, and I believe the issue is that the "Comment trashed" message appears on the notification before the delete request actually occurs. If you close the browser window immediately after deleting the comment, it isn't actually deleted. If you leave the browser window opens for a couple seconds, the comment is deleted as expected.

### PR DESCRIPTION
**Pull request by alisterscott**
As @rachelmcr pointed out in #535, closing the browser quickly after clicking trash doesn't actually send the request to delete the comment.

This PR waits until the 'Undo' button disappears so that the request is sent (rather than waiting for an arbitrary time).

Fixes #535

### CODE REVIEW

**Comment by alisterscott** [comment]
@rachelmcr: would you mind 👀 at this to see whether it fixes #535?

File: specs/wp-notifications-spec.js [hunk 1]
```diff
@@ -98,7 +98,8 @@ test.describe( 'Notifications: (' + screenSize + ') @parallel', function() {
 					test.it( 'Can delete the comment', function() {
```
Comment (hoverduck) [inline specs/wp-notifications-spec.js]: As long as you're in here can you update this step description to something like "Can delete the comment (and wait for UNDO grace period)" so there's some indication for anyone watching why this step is taking so long?
