### PR TITLE
Fix activity log test

### LINKED ISSUE #1413: Re-enable Activity Log Test
When A/L is available again re-enable this test

### PR DESCRIPTION
**Pull request by alisterscott**
Re-enables the activity log test

Updates the selector that finds the activity log entry for publishing a post

Closes #1413

### CODE REVIEW

File: lib/pages/stats/activity-page.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ export default class ActivityPage extends AsyncBaseContainer {
 				.isElementPresent(
 					driver,
 					By.xpath(
-						`//div[@class='activity-log-item__description-content']//a//em[text()='${ postTitle }']`
+						`//div[@class='activity-log-item__description-content']//a[text()='${ postTitle }']`
 					)
 				)
 				.then( present => {
```
Comment (Stojdza) [inline lib/pages/stats/activity-page.js]: Should we consider and put async instead `.then` in this method?

Comment (alisterscott) [reply lib/pages/stats/activity-page.js]: Good idea - fixed 👍
